name: Test Pull Request (${language})

on:
  pull_request:
    branches:
    - main
    paths:
    - '${language}/**'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test ${language} Samples
      run: |
        ./scripts/smoke.sh --suite ${language} \
                           --builder paketobuildpacks/builder:full \
                           --builder paketobuildpacks/builder:base \
                           --builder paketobuildpacks/builder:tiny
