name: Test Pull Request (${language})

on:
  pull_request:
    branches:
    - main
    paths:
    - '${language}/**'
    - '.github/workflows/test-pull-request-${language}.yml'

concurrency:
  # only one instance of test suite per PR at one time
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        builder:
        - 'paketobuildpacks/builder-jammy-full:latest'
        - 'paketobuildpacks/builder-jammy-base:latest'
        - 'paketobuildpacks/builder-jammy-tiny:latest'
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test ${language} Samples
      run: |
        ./scripts/smoke.sh --suite ${language} \
                           --builder ${{ matrix.builder }}
