name: akka
"on":
  pull_request:
    paths:
    - java/akka/**
  push:
    branches:
    - main
    paths:
    - java/akka/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('java/akka/build.sbt') }}
          restore-keys: ${{ runner.os }}-sbt
      - run: ./sbt universal:packageBin
        working-directory: java/akka
