name: Test Pull Request (Procfile)

on:
  merge_group:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/test-pull-request-procfile.yml'
    - 'procfile/**'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.x

    - name: Checkout
      uses: actions/checkout@v6
    
    - uses: buildpacks/github-actions/setup-pack@v5.10.0

    - name: Test Procfile Samples
      run: |
        cd procfile/procfile-sample
        pack build applications/procfile \
          --builder docker.io/paketobuildpacks/ubuntu-noble-builder-buildpackless:latest \
          --buildpack docker.io/paketobuildpacks/go-dist \
          --buildpack docker.io/paketocommunity/build-plan \
          --buildpack docker.io/paketobuildpacks/procfile
