name: Test Pull Request (git)

on:
  pull_request:
    branches:
    - main
    paths:
    - 'git/**'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test git Samples
      run: |
        ./scripts/smoke.sh --suite git \
                           --builder paketobuildpacks/builder:full \
                           --builder paketobuildpacks/builder:base
