name: Test Pull Request (web-servers)

on:
  merge_group:
  pull_request:
    branches:
    - main
    paths:
    - 'web-servers/**'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.x

    - name: Checkout
      uses: actions/checkout@v6

    - name: Test Web Servers Samples
      run: |
        cd web-servers/nginx-sample
        pack build applications/nginx \
          --builder docker.io/paketobuildpacks/ubuntu-noble-builder:latest \
          --lifecycle-image buildpacksio/lifecycle:e10cf01 \
          --buildpack urn:cnb:builder:paketo-buildpacks/web-servers
