name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test Sample Apps With Latest Paketo Builders
      run: |
        ./scripts/smoke.sh --builder paketobuildpacks/builder:full \
                   --builder paketobuildpacks/builder:base \
                   --builder paketobuildpacks/builder:tiny

