name: Test Pull Request (git)

on:
  merge_group:
  pull_request:
    branches:
    - main
    paths:
    - 'git/**'

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.22.x

    - name: Checkout
      uses: actions/checkout@v5

    - name: Test git Samples
      run: |
        ./scripts/smoke.sh --suite git \
                           --builder paketobuildpacks/builder-jammy-full:latest \
                           --builder paketobuildpacks/builder-jammy-base:latest
